import { Alien, JourneyStep, GalleryItem } from './types';

// Image assets generated by the AI agent
export const HERO_IMAGE = '/src/assets/images/ben10_hero_1782560694317.jpg';
export const OMNITRIX_CORE = '/src/assets/images/omnitrix_core_1782560711450.jpg';
export const LINEUP_IMAGE = '/src/assets/images/aliens_lineup_1782560730840.jpg';

export const ALIENS_DATA: Alien[] = [
  {
    id: 'heatblast',
    name: 'HEATBLAST',
    species: 'Pyronite',
    homeworld: 'Pyros',
    description: 'A magma-based life form who can control extreme heat, shoot fireballs from his hands, create magma streams to fly on, and absorb fire to put out flames. He is Ben’s ultimate pyrokinesis tool.',
    quote: 'It’s time to turn up the heat!',
    abilities: ['Fire Generation', 'Heat Absorption', 'Magma Surfing', 'Superhuman Durability', 'Flight (via Fire Disc)'],
    stats: {
      strength: 7,
      speed: 6,
      intelligence: 6,
      agility: 7,
      energy: 10,
      fighting: 7
    },
    color: 'text-amber-500 shadow-amber-500/50',
    accentColor: '#f59e0b',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=500&q=80', // Magma-like digital render
    trivia: 'Heatblast was the very first alien transformation Ben ever unlocked, accidentally setting Grandpa Max’s campsite on fire!'
  },
  {
    id: 'xlr8',
    name: 'XLR8',
    species: 'Kineceleran',
    homeworld: 'Kinet',
    description: 'XLR8 can manipulate friction, allowing him to reach speeds of over 500 mph in seconds. He can run on vertical surfaces, cross water bodies easily, and create powerful localized tornadoes.',
    quote: 'Missed me? Speed is my middle name!',
    abilities: ['Superhuman Speed', 'Friction Manipulation', 'Wall-Running', 'Tornado Creation', 'Prehensile Tail'],
    stats: {
      strength: 4,
      speed: 10,
      intelligence: 7,
      agility: 9,
      energy: 5,
      fighting: 8
    },
    color: 'text-cyan-400 shadow-cyan-400/50',
    accentColor: '#22d3ee',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=500&q=80', // Tech-cyan abstract digital speed
    trivia: 'XLR8’s visor slides down automatically when he runs to protect his eyes from high-speed space debris and wind shear.'
  },
  {
    id: 'fourarms',
    name: 'FOUR ARMS',
    species: 'Tetramand',
    homeworld: 'Khoros',
    description: 'A 12-foot-tall, red-skinned powerhouse with four massive arms. He possesses unmatched physical strength, dense armored skin, and can create devastating shockwaves by clapping his hands.',
    quote: 'Need a hand? How about four of them!',
    abilities: ['Super Strength', 'Shockwave Hand Claps', 'Immense Leaping', 'Dense Body Armor', 'Enhanced Durability'],
    stats: {
      strength: 10,
      speed: 5,
      intelligence: 4,
      agility: 6,
      energy: 4,
      fighting: 9
    },
    color: 'text-red-500 shadow-red-500/50',
    accentColor: '#ef4444',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=500&q=80', // Crimson powerful abstract artwork
    trivia: 'On Khoros, female Tetramands are actually stronger and faster than males, making Gwen’s version slightly superior!'
  },
  {
    id: 'greymatter',
    name: 'GREY MATTER',
    species: 'Galvan',
    homeworld: 'Galvan Prime',
    description: 'A tiny, grey-skinned alien barely five inches tall, but with an intellect that can solve any galactic crisis. Grey Matter excels at hacking, understanding complex machinery, and organic systems.',
    quote: 'Size doesn’t matter when you have a brain like this.',
    abilities: ['Hyper Intellect', 'Micro-Scaling Navigation', 'Advanced Technology Hacking', 'Wall Climbing', 'High-Pressure Jaw'],
    stats: {
      strength: 1,
      speed: 4,
      intelligence: 10,
      agility: 8,
      energy: 2,
      fighting: 3
    },
    color: 'text-green-400 shadow-green-400/50',
    accentColor: '#4ade80',
    imageUrl: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&w=500&q=80', // Abstract scientific matrix grid
    trivia: 'The creator of the Omnitrix itself, Azmuth, is a Galvan, which is why Grey Matter understands its mechanical core so well.'
  },
  {
    id: 'diamondhead',
    name: 'DIAMONDHEAD',
    species: 'Petrosapien',
    homeworld: 'Petropia',
    description: 'An organic crystal alien composed of hyper-dense Taydenite. He can grow crystal shards, morph his limbs into sharp blades or shields, reflect lasers, and control surrounding crystal structures.',
    quote: 'Solid as crystal, unbreakable as my spirit!',
    abilities: ['Crystallokinesis', 'Weapon Morphing', 'Laser Reflection', 'Regenerative Armor', 'Shard Launching'],
    stats: {
      strength: 8,
      speed: 5,
      intelligence: 6,
      agility: 6,
      energy: 8,
      fighting: 8
    },
    color: 'text-emerald-400 shadow-emerald-400/50',
    accentColor: '#34d399',
    imageUrl: 'https://images.unsplash.com/photo-1551732998-9573f695fdbb?auto=format&fit=crop&w=500&q=80', // Emerald crystal structures
    trivia: 'Since Diamondhead is made of crystals, he is highly vulnerable to sonic vibrations, which can cause his body to crack.'
  },
  {
    id: 'wildmutt',
    name: 'WILDMUTT',
    species: 'Vulpimancer',
    homeworld: 'Vulpin',
    description: 'A beast-like alien with no eyes, but highly developed olfactory and auditory senses. Wildmutt perceives the world through thermography, tracks scents across light years, and is incredibly agile.',
    quote: '*ROOOOOAAAAR* (Communicates through primal instinct)',
    abilities: ['Radar Senses', 'Enhanced Scent Tracking', 'Quill Shooting', 'Prehensile Grip', 'Gymnastic Agility'],
    stats: {
      strength: 7,
      speed: 8,
      intelligence: 3,
      agility: 9,
      energy: 1,
      fighting: 8
    },
    color: 'text-orange-500 shadow-orange-500/50',
    accentColor: '#f97316',
    imageUrl: 'https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?auto=format&fit=crop&w=500&q=80', // Primal glowing orange abstract texture
    trivia: 'Wildmutt is the only alien in the original Omnitrix roster that does not speak English, communicating solely in growls and snarls.'
  },
  {
    id: 'ripjaws',
    name: 'RIPJAWS',
    species: 'Piscciss Volann',
    homeworld: 'Piscciss',
    description: 'The master of deep waters. Ripjaws has steel-shredding jaws, a bio-luminescent light lure, and a lower body that transforms into a fish tail for high-speed swimming. He requires constant hydration.',
    quote: 'Ready to dive into action!',
    abilities: ['High-Velocity Swimming', 'Steel-Crushing Bite', 'Water Adaptation', 'Luminescent Attraction', 'Tail Transformation'],
    stats: {
      strength: 6,
      speed: 9, // Water speed (5 land speed)
      intelligence: 5,
      agility: 7,
      energy: 3,
      fighting: 7
    },
    color: 'text-teal-400 shadow-teal-400/50',
    accentColor: '#2dd4bf',
    imageUrl: 'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?auto=format&fit=crop&w=500&q=80', // Deep ocean teal mystery
    trivia: 'Ripjaws is incredibly powerful underwater, but if he stays in dry environments for too long, he will rapidly dehydrate.'
  },
  {
    id: 'cannonbolt',
    name: 'CANNONBOLT',
    species: 'Arburian Pelarota',
    homeworld: 'Arburia',
    description: 'A bulky alien covered in heavy yellow armor plates. Cannonbolt can curl into a perfect sphere, accelerating to extreme velocities. He is impervious to lava, acid, and heavy laser impacts.',
    quote: 'Let’s roll!',
    abilities: ['Sphere Transformation', 'High-Speed Rolling', 'Kinetic Charge', 'Laser-Proof Armor', 'Shockwave Impact'],
    stats: {
      strength: 8,
      speed: 8, // in ball form (4 in normal form)
      intelligence: 5,
      agility: 5,
      energy: 2,
      fighting: 7
    },
    color: 'text-yellow-400 shadow-yellow-400/50',
    accentColor: '#facc15',
    imageUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=500&q=80', // Yellow spherical energy
    trivia: 'Cannonbolt was the first "unlocked" alien outside of the original 10, added automatically when the Omnitrix detected a new cosmic DNA signature.'
  }
];

export const JOURNEY_STEPS: JourneyStep[] = [
  {
    id: '1',
    title: 'THE DISCOVERY',
    subtitle: 'The Omnitrix Lands',
    description: 'While on a summer road trip with Grandpa Max and Gwen, Ben finds a mysterious escape pod carrying the Omnitrix. The device attaches to his wrist, introducing him to 10 alien heroes.',
    year: 'SEASON 1',
    phase: 'Discovered'
  },
  {
    id: '2',
    title: 'FIRST HEROIC BATTLES',
    subtitle: 'Facing Vilgax',
    description: 'Ben faces galactic warlord Vilgax, learning the responsibilities of being Earth’s guardian. He realizes the Omnitrix is not a toy, but a key to universal peace.',
    year: 'SEASON 2',
    phase: 'First Battle'
  },
  {
    id: '3',
    title: 'THE DNA EXPANSION',
    subtitle: 'Master Control Unlocked',
    description: 'New alien DNAs like Cannonbolt and Wildvine are unlocked. Ben temporarily accesses the Master Control, allowing voice-activated instant transformations without cooldowns.',
    year: 'SEASON 3',
    phase: 'Grows Stronger'
  },
  {
    id: '4',
    title: 'SAVING THE CREATOR',
    subtitle: 'Secret of the Omnitrix',
    description: 'The Omnitrix enters Self-Destruct Mode. Ben travels across space to find the creator, Azmuth, to repair the device and unlocks Way Big to defeat Vilgax’s armada.',
    year: 'SEASON 4',
    phase: 'Protects Earth'
  },
  {
    id: '5',
    title: 'THE LEGEND CONTINUES',
    subtitle: 'Ultimate Alien Legacy',
    description: 'As Ben grows older, his arsenal expands to thousands of aliens. He remains the premier hero of Earth, working with Plumbers to maintain galactic security.',
    year: 'BEYOND',
    phase: 'Legend Continues'
  }
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'g1',
    title: 'Classic Ben Tennyson',
    category: 'characters',
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80',
    description: 'Ben ready to tap the Omnitrix and go hero mode.'
  },
  {
    id: 'g2',
    title: 'Heatblast Cosmic Roar',
    category: 'aliens',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    description: 'A Pyronite channeling supercharged volcanic heat.'
  },
  {
    id: 'g3',
    title: 'Battle for Bellwood',
    category: 'battles',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    description: 'A clash of cosmic energies against alien invaders.'
  },
  {
    id: 'g4',
    title: 'Gwen’s Magic Sphere',
    category: 'characters',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    description: 'Gwen Tennyson casting mana shields to support Ben.'
  },
  {
    id: 'g5',
    title: 'XLR8 Neon Chase',
    category: 'aliens',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    description: 'Hyper-detailed velocity blur on a neon speed-strip.'
  },
  {
    id: 'g6',
    title: 'Vilgax’s Flagship',
    category: 'episodes',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    description: 'The terrifying visual outline of Vilgax’s space dreadnought.'
  },
  {
    id: 'g7',
    title: 'Omnitrix Schematic HUD',
    category: 'wallpapers',
    imageUrl: OMNITRIX_CORE,
    description: 'Emerald schematics of the core dial matrix.'
  },
  {
    id: 'g8',
    title: 'The Rust Bucket',
    category: 'episodes',
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80',
    description: 'Grandpa Max’s modified plumbing RV cruising through desert highways.'
  },
  {
    id: 'g9',
    title: 'Grandpa Max Tennyson',
    category: 'characters',
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
    description: 'Retired Magister Max Tennyson, coordinates of Plumber Command.'
  }
];
